[versions]
kotlin = "2.2.21"


[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version = "3.5.7" }
reactor-kafka = { group = "io.projectreactor.kafka", name = "reactor-kafka", version = "1.3.25" }
kafka-clients = { group = "org.apache.kafka", name = "kafka-clients", version = "4.1.1" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.12.1" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
